name: Mkdocs CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Deploy MkDocs with customed awesome plugin'
      runs:
        using: 'docker'
        image: 'Dockerfile'
